### ISSUE TITLE
Adopt BEM methodology with a prefix

### ISSUE THREAD

**Issue by vojtechszocs** [kubevirt/web-ui-components#137]
Based on [Sam's review comment](https://github.com/openshift/console/pull/888#discussion_r237997882), I think it makes sense to adopt [BEM](http://getbem.com/) methodology together with using a `kubevirt` prefix.

This should give our styles a better structure and avoid potential clashes with the target application.

Taking `sass/components/_VmStatus.scss` as an example:

```css
/* before */
.vm-status-icon { margin-right: 5px; }

/* after */
.kubevirt-vm-status__icon { margin-right: 5px; }
```
